#!/bin/sh

RELEASEBRANCH="patch8"
SQUASHBRANCH="squashed8"
CLIENTBRANCH="client8"
AMPACHEDIR=$PWD
COMPOSERPATH="/usr/local/bin/composer"

# Ampache 8 requires PHP 8.5+ (composer.json "php": ">=8.5") so there are no 8.2/8.3/8.4 builds.
ZIPEXCLUDE="--exclude=./config/ampache.cfg.php --exclude=./docker/* --exclude=./node_modules/* --exclude=./.git/* --exclude=./.github/* --exclude=./.tx/* --exclude=./.idea/* --exclude=.gitignore --exclude=.gitattributes --exclude=.scrutinizer.yml --exclude=CNAME --exclude=.codeclimate.yml --exclude=.php* --exclude=.tgitconfig --exclude=.travis.yml"
# Tracked files that no runtime install needs. These stay in git and are only kept out of the zips,
# so they are excluded here rather than deleted from the build trees.
# NOTE composer.lock, package-lock.json, package.json and vite.config.js are deliberately NOT excluded,
# the code-only zips still have to run `composer install` and `npm install` against them.
ZIPEXCLUDE="$ZIPEXCLUDE --exclude=./tests/* --exclude=./phpunit.xml --exclude=./phpstan.neon --exclude=./phpstan-baseline.neon --exclude=./rector.php --exclude=./docker-compose.yml"
# The openapi spec is a development reference and is published on ampache.org (4MB of the two files)
ZIPEXCLUDE="$ZIPEXCLUDE --exclude=./docs/openapi*.json"
# prettyPhoto ships its demo gallery images (1.2MB) which nothing in Ampache links to.
# Leading * (not */) so one pattern matches all three structures: public/lib, lib and public/client/lib.
ZIPEXCLUDE="$ZIPEXCLUDE --exclude=*lib/modules/prettyphoto/images/fullscreen/*"
# Dead webfont formats: .eot is IE8 only, .svg is iOS Safari 4 only. .woff and .ttf cover every browser
# that can run Ampache, and the @font-face src: list only fetches the format the browser actually picks.
ZIPEXCLUDE="$ZIPEXCLUDE --exclude=*themes/*/templates/fonts/*.eot --exclude=*themes/*/templates/fonts/*.svg"
ZIPEXCLUDEPUBLIC="--exclude=./public/rest/.htaccess --exclude=./public/play/.htaccess --exclude=./public/channel/.htaccess"
ZIPEXCLUDESQUASHED="--exclude=./rest/.htaccess --exclude=./play/.htaccess --exclude=./channel/.htaccess"

# Trim generated trees (vendor/, lib/components/, material-symbols/) down to what the app loads at runtime.
# MUST be called after composer install AND npm install/build/minify have finished, never before:
# everything it touches is either regenerated by those steps or restored by the `git reset --hard` at the
# top of the next run, so nothing it removes is still needed by an install.
prune_release_tree() {
  # 1. javascript/css source maps. Devtools only, the app never fetches them.
  find . \( -path ./node_modules -o -path ./.git \) -prune -o -name '*.map' -type f -exec rm -f {} +

  # 2. bootstrap ships every build variant. Ampache only ever loads bootstrap.min.css and bootstrap.min.js
  # (see public/templates/install_header.inc.php and friends), so drop rtl, esm and the unminified builds.
  find . -path '*/components/bootstrap/*' -type f \( -name '*rtl*' -o -name '*esm*' \) -delete
  find . -path '*/components/bootstrap/*' -type f \( -name '*.css' -o -name '*.js' \) ! -name '*.min.*' -delete

  # 3. per-package test/doc/example dirs, skipping any dir composer's autoloader actually points at
  # (nabil1337/case-helper really does autoload its own tests/ dir, and others may follow).
  if [ -d ./vendor/composer ]; then
    find ./vendor -mindepth 3 -maxdepth 3 -type d \
      \( -name tests -o -name test -o -name Tests -o -name Test -o -name docs -o -name doc \
         -o -name examples -o -name example -o -name benchmarks -o -name .github \) | while read -r dir; do
      rel=`echo "$dir" | sed 's#^\./vendor/##'`
      if grep -qF "$rel" ./vendor/composer/autoload_*.php 2>/dev/null; then
        echo "  keeping autoloaded vendor dir: $rel"
      else
        rm -rf "$dir"
      fi
    done
  fi

  # 4. getid3 windows helper binaries (cygwin1.dll, metaflac.exe, ...). getid3 only looks for these behind
  # GETID3_OS_ISWINDOWS and downgrades to a startup_warning when the dir is absent, so this is a no-op on
  # a linux/bsd server. Drop this line if the windows builds should keep tag writing helpers.
  rm -rf ./vendor/james-heinrich/getid3/helperapps

  # 5. npm pulls all 6474 @material-symbols icons into resources/images/material-symbols but Ui::get_material_symbol()
  # only ever resolves the handful named in the source. Build a deliberately over-broad whitelist (every quoted
  # lowercase token in the tree, so names passed through a variable like Ajax::button() are still caught) and drop
  # the rest. A missing icon is non-fatal anyway, Ui::get_material_symbol() falls back to icon_error.svg.
  ICONDIR=./resources/images/material-symbols
  if [ -d "$ICONDIR" ]; then
    KEEP=`mktemp`; ALL=`mktemp`; DROP=`mktemp`
    find . \( -path ./node_modules -o -path ./.git -o -path ./vendor -o -path "$ICONDIR" \) -prune -o \
      -type f \( -name '*.php' -o -name '*.js' -o -name '*.inc' -o -name '*.html' -o -name '*.css' \) \
      -exec grep -hoE "['\"][a-z0-9][a-z0-9_-]{1,40}['\"]" {} + | tr -d "\"'" | sort -u > "$KEEP"
    find "$ICONDIR" -name '*.svg' -exec basename {} .svg \; | sort -u > "$ALL"
    comm -12 "$ALL" "$KEEP" > "$DROP".keep
    comm -23 "$ALL" "$KEEP" > "$DROP"
    KEPT=`wc -l < "$DROP".keep`
    # fail safe: if the scan came back implausibly empty something broke, keep every icon rather than ship a bald ui
    if [ "$KEPT" -lt 100 ]; then
      echo "  WARNING: icon scan only matched $KEPT icons, keeping all `wc -l < "$ALL"` icons"
    else
      while read -r icon; do rm -f "$ICONDIR/$icon.svg"; done < "$DROP"
      echo "  material-symbols: kept $KEPT icons, removed `wc -l < "$DROP"`"
    fi
    rm -f "$KEEP" "$ALL" "$DROP" "$DROP".keep
  fi
}

# Assert a release tree is exactly what its transform script produces from the
# current patch8. A squashed8/client8 branch that was hand-edited, or that was
# never rebuilt after patch8 moved, ships requires and rewrite targets that do
# not resolve - and nothing downstream of here would notice. Runs before any
# composer/npm work so a bad branch costs seconds, not a full build.
#
# The transforms are idempotent, so this is a no-op on a compliant tree. On a
# non-compliant one it leaves the tree modified, which is fine: we exit before
# the zip and the next run starts with `git reset --hard`.
check_structure() {
  tree=$1
  script=$2
  name=`basename "$tree"`

  cd "$tree" || exit 1
  if ! git diff --quiet HEAD; then
    echo "ERROR: $name has uncommitted changes before the structure check"
    git status --short
    exit 1
  fi

  cd $AMPACHEDIR
  log=`mktemp`
  if ! python3 "./$script" "$AMPACHEDIR/ampache-patch8/public" "$tree" > "$log" 2>&1; then
    echo "ERROR: $script failed against $name"
    tail -20 "$log"
    rm -f "$log"
    exit 1
  fi
  if grep -q '^STALE:' "$log"; then
    echo "ERROR: $name still ships files the patch8 branch has removed"
    grep '^STALE:' "$log"
    rm -f "$log"
    exit 1
  fi
  rm -f "$log"

  cd "$tree"
  if ! git diff --quiet HEAD; then
    echo "ERROR: $name does not match the output of $script"
    echo "       the branch needs rebuilding from patch8 before this release"
    git --no-pager diff --stat HEAD
    exit 1
  fi

  cd $AMPACHEDIR
  echo "  structure OK: $name"
}

if [ ! -d $AMPACHEDIR/ampache-patch8 ]; then
  git clone -b patch8 https://github.com/ampache/ampache.git ampache-patch8
fi
if [ ! -f $AMPACHEDIR/ampache-patch8/index.php ]; then
  rm -rf $AMPACHEDIR/ampache-patch8
  git clone -b patch8 https://github.com/ampache/ampache.git ampache-patch8
fi
cd $AMPACHEDIR/ampache-patch8 && git fetch origin $RELEASEBRANCH && git checkout -f $RELEASEBRANCH && git reset --hard origin/$RELEASEBRANCH && git pull

RELEASEVERSION=`grep -oP '[0-9]+\.[0-9]+\.[0-9]+' $AMPACHEDIR/ampache-patch8/src/Config/Init/InitializationHandlerConfig.php`
if [ ! $# -eq 0 ]; then
  RELEASEVERSION=$1
fi

echo
echo $RELEASEVERSION
echo

if [ ! -d $AMPACHEDIR/releases ]; then
  mkdir $AMPACHEDIR/releases
fi
if [ ! -d $AMPACHEDIR/releases/8 ]; then
  mkdir $AMPACHEDIR/releases/8
fi

if [ ! -f $COMPOSERPATH ]; then
  COMPOSERPATH="$AMPACHEDIR/docker/composer"
  wget -q -O $COMPOSERPATH https://getcomposer.org/download/latest-stable/composer.phar
  chmod +x $COMPOSERPATH
fi
cd $AMPACHEDIR/releases/8
if [ ! -d $AMPACHEDIR/releases/8/generic ]; then
  git clone -b $RELEASEBRANCH https://github.com/ampache/ampache.git generic
fi
if [ ! -d $AMPACHEDIR/releases/8/generic_squashed ]; then
  git clone -b $SQUASHBRANCH https://github.com/ampache/ampache.git generic_squashed
fi
if [ ! -d $AMPACHEDIR/releases/8/generic_client ]; then
  git clone -b $CLIENTBRANCH https://github.com/ampache/ampache.git generic_client
fi

if [ ! -d $AMPACHEDIR/releases/8/php85 ]; then
  git clone -b $RELEASEBRANCH https://github.com/ampache/ampache.git php85
fi
if [ ! -f $AMPACHEDIR/releases/8/php85/index.php ]; then
  rm -rf $AMPACHEDIR/releases/8/php85
  git clone -b $RELEASEBRANCH https://github.com/ampache/ampache.git php85
fi
if [ ! -d $AMPACHEDIR/releases/8/php85_squashed ]; then
  git clone -b $SQUASHBRANCH https://github.com/ampache/ampache.git php85_squashed
fi
if [ ! -f $AMPACHEDIR/releases/8/php85_squashed/index.php ]; then
  rm -rf $AMPACHEDIR/releases/8/php85_squashed
  git clone -b $SQUASHBRANCH https://github.com/ampache/ampache.git php85_squashed
fi
if [ ! -d $AMPACHEDIR/releases/8/php85_client ]; then
  git clone -b $CLIENTBRANCH https://github.com/ampache/ampache.git php85_client
fi
if [ ! -f $AMPACHEDIR/releases/8/php85_client/index.php ]; then
  rm -rf $AMPACHEDIR/releases/8/php85_client
  git clone -b $CLIENTBRANCH https://github.com/ampache/ampache.git php85_client
fi

# force reset everything
cd $AMPACHEDIR/releases/8/generic && git fetch origin $RELEASEBRANCH && git checkout -f $RELEASEBRANCH && git reset --hard origin/$RELEASEBRANCH && git pull
cd $AMPACHEDIR/releases/8/generic_squashed && git fetch origin $SQUASHBRANCH && git checkout -f $SQUASHBRANCH && git reset --hard origin/$SQUASHBRANCH && git pull
cd $AMPACHEDIR/releases/8/generic_client && git fetch origin $CLIENTBRANCH && git checkout -f $CLIENTBRANCH && git reset --hard origin/$CLIENTBRANCH && git pull
cd $AMPACHEDIR/releases/8/php85 && git fetch origin $RELEASEBRANCH && git checkout -f $RELEASEBRANCH && git reset --hard origin/$RELEASEBRANCH && git pull
cd $AMPACHEDIR/releases/8/php85_squashed && git fetch origin $SQUASHBRANCH && git checkout -f $SQUASHBRANCH && git reset --hard origin/$SQUASHBRANCH && git pull
cd $AMPACHEDIR/releases/8/php85_client && git fetch origin $CLIENTBRANCH && git checkout -f $CLIENTBRANCH && git reset --hard origin/$CLIENTBRANCH && git pull

# verify the derived structures before spending anything on them
echo
echo "checking structures against $RELEASEBRANCH"
check_structure $AMPACHEDIR/releases/8/generic_squashed squash-ampache8.py
check_structure $AMPACHEDIR/releases/8/generic_client client-ampache8.py
check_structure $AMPACHEDIR/releases/8/php85_squashed squash-ampache8.py
check_structure $AMPACHEDIR/releases/8/php85_client client-ampache8.py
echo

# GENERIC (No composer packages installed)
cd $AMPACHEDIR/releases/8/generic
rm -rf vendor/* public/lib/components/*
find . -xtype l -exec rm {} \;
find . -name "*.map.1" -exec rm {} \;
prune_release_tree

cd $AMPACHEDIR/releases/8/generic_squashed
rm -rf vendor/* ./lib/components/* ./docker/
find . -xtype l -exec rm {} \;
find . -name "*.map.1" -exec rm {} \;
prune_release_tree

cd $AMPACHEDIR/releases/8/generic_client
rm -rf vendor/* public/client/lib/components/*
find . -xtype l -exec rm {} \;
find . -name "*.map.1" -exec rm {} \;
prune_release_tree

# php 8.5
cd $AMPACHEDIR/releases/8/php85
rm -rf vendor/* public/lib/components/*
php8.5 $COMPOSERPATH install --no-dev || exit 1
npm install || exit 1
npm run build || exit 1
npm run minify || exit 1
git diff --quiet -- '*jplayer*' || { echo "ERROR: committed jplayer minified files were stale in php85"; exit 1; }
find . -xtype l -exec rm {} \;
find . -name "*.map.1" -exec rm {} \;
prune_release_tree

cd $AMPACHEDIR/releases/8/php85_squashed
rm -rf vendor/* ./lib/components/* ./docker/
php8.5 $COMPOSERPATH install --no-dev || exit 1
npm install || exit 1
npm run build || exit 1
npm run minify || exit 1
git diff --quiet -- '*jplayer*' || { echo "ERROR: committed jplayer minified files were stale in php85_squashed"; exit 1; }
find . -xtype l -exec rm {} \;
find . -name "*.map.1" -exec rm {} \;
prune_release_tree

cd $AMPACHEDIR/releases/8/php85_client
rm -rf vendor/* public/client/lib/components/*
php8.5 $COMPOSERPATH install --no-dev || exit 1
npm install || exit 1
npm run build || exit 1
npm run minify || exit 1
git diff --quiet -- '*jplayer*' || { echo "ERROR: committed jplayer minified files were stale in php85_client"; exit 1; }
find . -xtype l -exec rm {} \;
find . -name "*.map.1" -exec rm {} \;
prune_release_tree

# remove possible old release files before building the new one
if [ -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_public.zip ]; then
  rm $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_public.zip
fi
if [ -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_squashed.zip ]; then
  rm $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_squashed.zip
fi
if [ -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_client.zip ]; then
  rm $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_client.zip
fi
if [ -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5.zip ]; then
  rm $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5.zip
fi
if [ -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_squashed.zip ]; then
  rm $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_squashed.zip
fi
if [ -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_client.zip ]; then
  rm $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_client.zip
fi

# Build Releases

## GENERIC
cd $AMPACHEDIR/releases/8/generic && zip -r -q -u -9 $ZIPEXCLUDE $ZIPEXCLUDEPUBLIC ./../../ampache-${RELEASEVERSION}_public.zip ./
cd $AMPACHEDIR/releases/8/generic_squashed && zip -r -q -u -9 $ZIPEXCLUDE $ZIPEXCLUDESQUASHED ./../../ampache-${RELEASEVERSION}_squashed.zip ./
cd $AMPACHEDIR/releases/8/generic_client && zip -r -q -u -9 $ZIPEXCLUDE $ZIPEXCLUDEPUBLIC ./../../ampache-${RELEASEVERSION}_client.zip ./

## php 8.5
cd $AMPACHEDIR/releases/8/php85 && zip -r -q -u -9 $ZIPEXCLUDE $ZIPEXCLUDEPUBLIC ./../../ampache-${RELEASEVERSION}_all_php8.5.zip ./
cd $AMPACHEDIR/releases/8/php85_squashed && zip -r -q -u -9 $ZIPEXCLUDE $ZIPEXCLUDESQUASHED ./../../ampache-${RELEASEVERSION}_all_php8.5_squashed.zip ./
cd $AMPACHEDIR/releases/8/php85_client && zip -r -q -u -9 $ZIPEXCLUDE $ZIPEXCLUDEPUBLIC ./../../ampache-${RELEASEVERSION}_all_php8.5_client.zip ./

# go back
cd $AMPACHEDIR

if [ ! -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_public.zip ]; then
  echo "ERROR " $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_public.zip
fi
if [ ! -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_squashed.zip ]; then
  echo "ERROR " $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_squashed.zip
fi
if [ ! -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_client.zip ]; then
  echo "ERROR " $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_client.zip
fi
if [ ! -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5.zip ]; then
  echo "ERROR " $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5.zip
fi
if [ ! -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_squashed.zip ]; then
  echo "ERROR " $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_squashed.zip
fi
if [ ! -f $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_client.zip ]; then
  echo "ERROR " $AMPACHEDIR/releases/ampache-${RELEASEVERSION}_all_php8.5_client.zip
fi

cd $AMPACHEDIR/releases
# echo the version checksum
echo
echo "# ${RELEASEVERSION}"
echo
echo "php8.5"
md5sum ./ampache-${RELEASEVERSION}_all_php8.5.zip
md5sum ./ampache-${RELEASEVERSION}_all_php8.5_squashed.zip
md5sum ./ampache-${RELEASEVERSION}_all_php8.5_client.zip
echo
echo "**UNSUPPORTED** Code only release. (Requires composer and npm install)"
md5sum ./ampache-${RELEASEVERSION}_public.zip
md5sum ./ampache-${RELEASEVERSION}_squashed.zip
md5sum ./ampache-${RELEASEVERSION}_client.zip
echo
echo "## Zip Version information"
echo
echo "If you aren't familiar which the project make sure you know [which zip](https://ampache.org/docs/information/which-zip) you need to download."
echo

# go home
cd $AMPACHEDIR

