version: '3'

services:
  ampachetest:
    build:
      context: .
      dockerfile: docker/Dockerfilephp74
    restart: on-failure
    ports:
      - "8989:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./ampache:/var/www/html
      - ./docker/log:/var/log/ampache
      - ./docker/media:/media
      - ./docker/art:/mnt/art
      - ./docker/music:/mnt/music
      - ./docker/podcast:/mnt/podcast
      - ./docker/upload:/mnt/upload
      - ./docker/video:/mnt/video

