version: '3'

services:
  ampache84_squashed:
    build:
      context: .
      dockerfile: Dockerfilephp84
    restart: on-failure
    ports:
      - "8481:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../php84_squashed:/var/www/html/public
      - ./log:/var/log/ampache
      - ./media:/media
      - ./art:/mnt/art
      - ./music:/mnt/music
      - ./podcast:/mnt/podcast
      - ./upload:/mnt/upload
      - ./video:/mnt/video

