version: '3'

services:
  test7ampache82:
    build:
      context: .
      dockerfile: Dockerfilephp82
    restart: on-failure
    ports:
      - "18280:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../release-test/php82:/var/www/html
      - ./log:/var/log/ampache
      - ./media:/media
      - ./art:/mnt/art
      - ./music:/mnt/music
      - ./podcast:/mnt/podcast
      - ./upload:/mnt/upload
      - ./video:/mnt/video

