version: '3'

services:
  testampache81_squashed:
    build:
      context: .
      dockerfile: Dockerfilephp81
    restart: on-failure
    ports:
      - "18181:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../release-test/php81_squashed:/var/www/html/public
      - ./log:/var/log/ampache
      - ./media:/media
      - ./media/art:/mnt/art
      - ./media/music:/mnt/music
      - ./media/podcast:/mnt/podcast
      - ./media/upload:/mnt/upload
      - ./media/video:/mnt/video

